replicaCount: 1

image:
  ks_controller_manager_repo: cr.d.xiaomi.net/kubesphereio/ks-controller-manager
  ks_controller_manager_tag: v3.1.1
  ks_apiserver_repo: cr.d.xiaomi.net/kubesphereio/ks-apiserver
  ks_apiserver_tag: v3.1.1
  ks_console_repo: cr.d.xiaomi.net/kubesphereio/ks-console
  ks_console_tag: v3.1.1
  ks_kubectl_repo: cr.d.xiaomi.net/kubesphereio/kubectl
  ks_kubectl_tag: v1.0.0
  nginx_ingress_controller_repo: cr.d.xiaomi.net/kubesphereio/nginx-ingress-controller
  nginx_ingress_controller_tag: v0.35.0
  defaultbackend_repo: cr.d.xiaomi.net/kubesphereio/defaultbackend-amd64
  defaultbackend_tag: 1.4
  bookinfo_productpage_v1_repo: cr.d.xiaomi.net/kubesphereio/examples-bookinfo-productpage-v1
  bookinfo_productpage_v1_tag: 1.16.2
  bookinfo_reviews_v1_repo: cr.d.xiaomi.net/kubesphereio/examples-bookinfo-reviews-v1
  bookinfo_reviews_v1_tag: 1.16.2
  bookinfo_details_v1_repo: cr.d.xiaomi.net/kubesphereio/examples-bookinfo-details-v1
  bookinfo_details_v1_tag: 1.16.2
  bookinfo_ratings_v1_repo: cr.d.xiaomi.net/kubesphereio/examples-bookinfo-ratings-v1
  bookinfo_ratings_v1_tag: 1.16.3
  pullPolicy: Always

config:
  create: true

console:
  type: NodePort
  port: 30880

kube_version: v1.21.3-mi-v1.21.3-dev

apiserver:
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 20m
      memory: 512Mi

controller:
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 30m
      memory: 512Mi

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: In
          values:
          - ""

nodeSelector: {}
tolerations: []
